### ISSUE TITLE
Move assets

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#185]
Let's add a `resources/js/` and `resources/css` directory for assets.

**Comment by naxvog** [comment]
If we implement https://github.com/tillkruss/redis-cache/issues/184 we could use the `asset` folder for actual plugin assets instead of using a more "non-standard" naming scheme for plugin assets.
`wordpress-plugin-deploy` instead uses the `.wordpress-org` folder for any WordPress plugin repository assets.

**Comment by tillkruss** [comment]
Fantastic.

**Comment by tillkruss** [comment]
Resolved with c694cc8be9849850ff17b87f0574bce106b256f2 and 6c93ee1ff18f0c91d43182f5295c4860e9a83ea6.
