### ISSUE TITLE
"Object Cache" admin-bar node

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#224]
How can this be the most useful?

- [ ] ~~Toggle via options in settings~~
- [x] Enabled by default?
- [x] Disabled via `WP_REDIS_DISABLE_ADMINBAR`
- [x] Add with priority of 998, just before Query Monitor? 
- [ ] Should we hide the admin dashboard as well via an option?

The node could be:

```
| Object Cache
| - Flush Cache
| - Show Metrics
| --------------
| Status: Connected
| 99.4%; 940/6; 98.09 KB
```

Related:

- https://onexa.nl/wordpress/toolbar-link-redis-object-cache/?v=3e8d115eb4b3
- https://wordpress.org/support/topic/fyi-flush-button-script-breaks-update/#post-13121765

**Comment by tillkruss** [comment]
@naxvog: Feedback?

**Comment by tillkruss** [comment]
See #272 as well.

**Comment by nickchomey** [comment]
I created this snippet, largely stolen from the WP OPcache plugin (https://wordpress.org/plugins/flush-opcache/), that seems to work for adding a button to the admin bar for clearing the Object Cache. I don't really know how to appropriately integrate it into redis-cache, but perhaps someone else could look over the code and work to integrate it here?

Otherwise, it can be added to your functions.php or a snippets plugin. 

https://github.com/nickchomey/flush-object-cache/blob/main/flush-object-cache.php

**Comment by JapeNZ** [comment]
This looks like almost exactly what I'm after :)
I asked the question on the wordpress plugin support here:
[Admin Bar options please](https://wordpress.org/support/topic/admin-bar-options-please/#post-16356240)

An admin bar dropdown with disable / enable and flush object cache options would be an excellent addition.
I realise some people aren't keen on admin bar dropdowns, so having it as an option you can deactivate as you suggest would probably be a good idea too.

Any idea when this might be availbale?

**Comment by s-a-s-k-i-a** [comment]
@tillkruss Could you please ad a Flush Object Cache admin bar button to the pro version of your plugin as well? Would be amazing! Also maybe add permissions too. Like allow admins to define user roles, that are allowed to see and use the flush object cache button / Object Cache (Pro) administrative pages.

Thanks a lot!
Saskia

**Comment by tillkruss** [comment]
@s-a-s-k-i-a It's coming in the next release 👍

**Comment by s-a-s-k-i-a** [comment]
@tillkruss Awesome! Thank you!
XO
