### ISSUE TITLE
Custom metrics collection

### ISSUE THREAD

**Issue by fleandro-obs** [rhubarbgroup/redis-cache#314]
Hi, we're currently rolling out wordpress monitoring using prometheus.

One of the most important things we need to keep track of is cache statistics.
Would it be possible to add hooks that report every redis call, with details such as the key, group, whether it was a hit or a miss (including in-memory cache)?

Currently we have `redis_object_cache_get`, for example, but this ignores in-memory cache, and most importantly, also ignores redis misses. This renders it unsuitable for the purposes described above.

Having those hooks in place would allow us (and whoever needs to) implement our own metrics collection tailored to our needs.
We'd be open to work with you on this.

**Comment by tillkruss** [comment]
Hi @fleandro-obs! 

Those hooks are fairly simple to add, feel free to submit a PR 🙂

>We'd be open to work with you on this.

I'm not sure I understand what you mean.

You might also want to consider [Object Cache Pro](https://objectcache.pro/), since it's already capable of logging all Redis calls and you can overwrite the in-memory methods 👌

**Comment by tillkruss** [comment]
@fleandro-obs: Fantastic! 👌
