### ISSUE TITLE
 Do not use Redis for unauthenticated users

### ISSUE THREAD

**Issue by loixiyo** [rhubarbgroup/redis-cache#427]
Hi,

I am using WPFastestCache and the developer told me that Redis Cache can affect the cache generation. He told me that it would be better if the Redis Cache is only used for authenticated users.

This way:
- Anonymous users will used the cache generated by WPFastestCache
- Logged in users will not use that cache and Redis will be used here to make their navigation faster

Is this possible with any configuration or hook?

Thanks!

**Comment by tillkruss** [comment]
>He told me that it would be better if the Redis Cache is only used for authenticated users.

The WPFastestCache developer doesn't seem to understand object caching in WordPress. His request is not possible, without risking data corruption.

**Comment by loixiyo** [comment]
I would be more than happy if you explained a bit more before just closing the ticket. 

Are you saying that the cache that WPFastestCache plugin does not depend on the results that Redis Cache is storing? So it does not matter if the users are authenticated or not, the Redis cache will store results to SQL queries, right?

Regards.

**Comment by tillkruss** [comment]
Sure thing. Object caching happens for nearly all requests. Fronted, backend, API. Logged in or not.

If your object cache (Redis) is warm, then the "page cache generation" would will be faster as well. 

If your object cache is cold (was just flushed) the the page cache generation would be a bit slower, because it will simultaneously warm up the object cache (which is fine).
